#ifndef BARCODEVIEWPLUGIN_GLOBAL_H
#define BARCODEVIEWPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BARCODEVIEWPLUGIN_LIBRARY)
#  define BARCODEVIEWPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BARCODEVIEWPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BARCODEVIEWPLUGIN_GLOBAL_H
